### ISSUE TITLE
Apollo code reading

### ISSUE THREAD

**Issue by Jolins** [daohu527/Dig-into-Apollo#20]
Thanks for the detailed code sharing. As a beginner, I have a few questions to ask:
1) which  Module to start learning apollo？
2) How to debug apollo using IDE？（like vscode or others）
Hope you can write a blog about the  basic debugging and learning of apollo！
Best wishes！

**Comment by daohu527** [comment]
Thanks for you feedback!

> 1.which Module to start learning apollo？

Normally, it depends on your needs, because apollo's modules are very complex, I suggest starting from the simple, cyber, routing or control modules is better.

> 2. How to debug apollo using IDE？

Debug is not a very good way, because it is difficult for you to run a single module, but you can run some test cases. You can use GDB or vscode to debug. this is a official document [link](https://github.com/ApolloAuto/apollo/blob/r5.5.0/docs/howto/how_to_build_and_debug_apollo_in_vscode_cn.md)

There is already some notes about how to learning apollo [doc](https://github.com/daohu527/Dig-into-Apollo#getting-started). It may not be too easy at first, I hope you can start by watching some videos, If you have any questions, please feel free to discuss.

Have fun!

**Comment by Jolins** [comment]
> Thanks for you feedback!
> 
> > 1.which Module to start learning apollo？
> 
> Normally, it depends on your needs, because apollo's modules are very complex, I suggest starting from the simple, cyber, routing or control modules is better.
> 
> > 1. How to debug apollo using IDE？
> 
> Debug is not a very good way, because it is difficult for you to run a single module, but you can run some test cases. You can use GDB or vscode to debug. this is a official document [link](https://github.com/ApolloAuto/apollo/blob/r5.5.0/docs/howto/how_to_build_and_debug_apollo_in_vscode_cn.md)
> 
> There is already some notes about how to learning apollo [doc](https://github.com/daohu527/Dig-into-Apollo#getting-started). It may not be too easy at first, I hope you can start by watching some videos, If you have any questions, please feel free to discuss.
> 
> Have fun!
