### ISSUE TITLE
当前代码隶属于apollo 哪个分支？

### ISSUE THREAD

**Issue by Brian1203** [daohu527/dig-into-apollo#44]
看到 planning 模块介绍和 apollo 最新分支对应不上。想请教一下 具体是哪个分支的代码阅读？

**Comment by daohu527** [comment]
thank you for your feedback, after realizing this problem I added the code branch tag. But due to the large time span when writing, some parts may not keep up with the latest version. Updating to the latest version will take time, probably by the end of the year! 

planning moudle base on 3.5.0 version, and you can ref to the [tag ](https://github.com/daohu527/dig-into-apollo/tree/r3.5.0)
